name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.5'
          cache: true

      - name: Fetch
        run: |
          mkdir -p dist
          go run . -output dist/sub.txt sources.txt

      - name: Upload
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: sub
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
